# Generated by Django 5.0 on 2024-12-28 22:19

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainermodel',
            name='specialties',
        ),
        migrations.RemoveField(
            model_name='sessionmodel',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='trainingwishmodel',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='participantcommentmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='participantcommentmodel',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='participantmodel',
            name='session',
        ),
        migrations.RemoveField(
            model_name='participantmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sessioncomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='sessioncomment',
            name='session',
        ),
        migrations.RemoveField(
            model_name='sessionmodel',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='trainermodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='TrainerNew',
        ),
        migrations.RemoveField(
            model_name='trainingwishmodel',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='session',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sessiondate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trainingroom',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='session',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='session',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trainingroom', verbose_name='Salle'),
        ),
        migrations.AddField(
            model_name='session',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.formation_image_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='session',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.formation', verbose_name='Formation'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='trainers', to='core.formation'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='trainers',
            field=models.ManyToManyField(related_name='sessions', to='core.trainer', verbose_name='Formateurs'),
        ),
        migrations.DeleteModel(
            name='FormationModel',
        ),
        migrations.DeleteModel(
            name='ParticipantCommentModel',
        ),
        migrations.DeleteModel(
            name='ParticipantModel',
        ),
        migrations.DeleteModel(
            name='SessionComment',
        ),
        migrations.DeleteModel(
            name='SessionModel',
        ),
        migrations.DeleteModel(
            name='TrainerModel',
        ),
        migrations.DeleteModel(
            name='TrainingWishModel',
        ),
    ]
