# Generated by Django 5.0 on 2024-12-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='modality',
            field=models.CharField(choices=[('presentiel', 'Présentiel'), ('distanciel', 'Distanciel'), ('hybride', 'Hybride')], default='presentiel', max_length=20, verbose_name='Modalité de formation'),
        ),
        migrations.AddField(
            model_name='formation',
            name='type',
            field=models.CharField(choices=[('initial', 'Formation Initiale'), ('continue', 'Formation Continue'), ('specialisation', 'Formation Spécialisation')], default='initial', max_length=20, verbose_name='Type de formation'),
        ),
    ]
