# Generated by Django 5.0 on 2024-12-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_formation_modality_formation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='modality',
        ),
        migrations.AddField(
            model_name='formation',
            name='modalities',
            field=models.CharField(choices=[('presentiel', 'Présentiel'), ('distanciel', 'Distanciel'), ('asynchrone', 'Asynchrone')], default='presentiel', max_length=100, verbose_name='Modalités de formation'),
        ),
    ]
