# Generated by Django 5.0 on 2024-12-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_formation_modality_formation_modalities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='modalities',
        ),
        migrations.AddField(
            model_name='formation',
            name='is_asynchrone',
            field=models.BooleanField(default=False, verbose_name='Asynchrone'),
        ),
        migrations.AddField(
            model_name='formation',
            name='is_distanciel',
            field=models.BooleanField(default=False, verbose_name='Distanciel'),
        ),
        migrations.AddField(
            model_name='formation',
            name='is_presentiel',
            field=models.BooleanField(default=True, verbose_name='Présentiel'),
        ),
    ]
