# Generated by Django 5.0 on 2024-12-28 23:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_formation_modalities_formation_is_asynchrone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Formateur', 'verbose_name_plural': 'Formateurs'},
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='user',
        ),
        migrations.AddField(
            model_name='trainer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email professionnel'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.trainer_photo_path, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='trainers', to='core.formation', verbose_name='Formations'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
    ]
