# Generated by Django 5.0 on 2024-12-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_trainer_options_remove_trainer_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessiondate',
            options={'ordering': ['date'], 'verbose_name': 'Date de session', 'verbose_name_plural': 'Dates de session'},
        ),
        migrations.AddField(
            model_name='user',
            name='rpe_association',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RPE ou Association'),
        ),
    ]
