# Generated by Django 5.0 on 2024-12-29 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_sessiondate_options_remove_session_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingwish',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_wishes', to='core.session', verbose_name='Session associée'),
        ),
    ]
