# Generated by Django 5.0 on 2024-12-29 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_trainingwish_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('formation_added', 'Nouvelle formation'), ('session_created', 'Session de formation créée'), ('wish_assigned', 'Souhait de formation assigné'), ('session_reminder', 'Rappel de session'), ('session_status_update', 'Mise à jour du statut de session'), ('general', 'Information générale')], max_length=50),
        ),
        migrations.AlterField(
            model_name='participantcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participantcomment',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_comments', to='core.sessionparticipant'),
        ),
    ]
