# Generated by Django 5.0 on 2025-01-26 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du RPE / Association')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RPE / Association',
                'verbose_name_plural': 'RPE / Associations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='other_rpe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Autre RPE / Association'),
        ),
        migrations.AddField(
            model_name='user',
            name='rpe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rpe', verbose_name='RPE / Association'),
        ),
    ]
