# Generated by Django 5.1.7 on 2025-04-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rpe_user_other_rpe_user_rpe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainers/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='specialties',
            field=models.ManyToManyField(blank=True, to='core.formation', verbose_name='Spécialités'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
