# Generated by Django 5.1.7 on 2025-04-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_trainer_created_at_alter_trainer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='formation',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='formation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='user',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='formations/images/', verbose_name='Image'),
        ),
    ]
