# Generated by Django 5.1.7 on 2025-04-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_trainer_latitude_trainer_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingroom',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='trainingroom',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code postal'),
        ),
    ]
