# Generated by Django 5.1.7 on 2025-04-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_trainingroom_city_trainingroom_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='session',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='session',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code postal'),
        ),
    ]
