# Generated by Django 5.1.7 on 2025-04-30 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_session_is_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRoomComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu du commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainingroom_comments', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.trainingroom', verbose_name='Salle de formation')),
            ],
            options={
                'verbose_name': 'Commentaire de salle',
                'verbose_name_plural': 'Commentaires de salles',
                'ordering': ['-created_at'],
            },
        ),
    ]
